"""Initial tables

Revision ID: b9756f1cf153
Revises: 
Create Date: 2026-04-29 13:06:17.071229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9756f1cf153'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_adverts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_parsed_adverts_auto_id'), 'parsed_adverts', ['auto_id'], unique=True)
    op.create_index(op.f('ix_parsed_adverts_phone_number'), 'parsed_adverts', ['phone_number'], unique=False)
    op.create_index(op.f('ix_parsed_adverts_title'), 'parsed_adverts', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsed_adverts_title'), table_name='parsed_adverts')
    op.drop_index(op.f('ix_parsed_adverts_phone_number'), table_name='parsed_adverts')
    op.drop_index(op.f('ix_parsed_adverts_auto_id'), table_name='parsed_adverts')
    op.drop_table('parsed_adverts')
    # ### end Alembic commands ###
